### ISSUE TITLE
Hardware Request

### ISSUE THREAD

**Issue by karishmabava** [xiangzhai/laserkbd#3]
Hi, 
Are you guys still making the hardware?

**Comment by xiangzhai** [comment]
Hi @karishmabava

Thanks for your attention!

Please feel free to contact the original author @cheaven Shikai Chen <shikai.chn@gmail.com>  He made this happened :)  And he is running Slamtec http://www.slamtec.com/en/  There are a lot of cool Products indeed :)

Cheers,
Leslie Zhai <zhaixiang@loongson.cn>

**Comment by karishmabava** [comment]
Thanks!
