### ISSUE TITLE
I have some questions necessary for a graduation project please

### ISSUE THREAD

**Issue by hsayed21** [xiangzhai/laserkbd#4]
1- Can I implement this project using a chip like Arduino or Raspberry Pi instead of PC ?
2- Some components I can't find them like **type of camera** and **power&socket PCB**

Thanks. :heart:

**Comment by xiangzhai** [comment]
Hi @hsayed21 

I argue that recognizing the user’s finger top and perform distance measurement is too expensive to Arduino AVR or Raspberry Pi ARM development boards.  There are some principle introduction written by the original author @cheaven in Chinese simplified:  http://www.csksoft.net/blog/post/lowcost.laserkbd_part1.html

Cheers,
Leslie Zhai

**Comment by hsayed21** [comment]
thank you for replying @xiangzhai 
> I argue that recognizing the user’s finger top and perform distance measurement is too expensive to Arduino AVR or Raspberry Pi ARM development boards. There are some principle introduction written by the original author @cheaven in Chinese simplified: http://www.csksoft.net/blog/post/lowcost.laserkbd_part1.html

I want to dispense with the computer
run as  a single product

**Comment by hsayed21** [comment]
@xiangzhai 
As for the components how I get them and If there is an alternative components, tell me

**Comment by hsayed21** [comment]
Sorry for many questions @xiangzhai 

In short, I want to run this project without using PC, Does it work? and HOW ?

**Comment by xiangzhai** [comment]
> As for the components how I get them and If there is an alternative components, tell me

There are many local electronic markets in China.  Welcome to the MAKER's heaven :)

> In short, I want to run this project without using PC, Does it work? and HOW ?

It needs to find some development boards which enable to run OpenCV recognition demo.  OpenCV is the most critical expensive part in the laserkbd.  The demo was able to work then ported the laserkbd to the development board.

**Comment by hsayed21** [comment]
> It needs to find some development boards which enable to run OpenCV recognition demo. OpenCV is the most critical expensive part in the laserkbd. The demo was able to work then ported the laserkbd to the development board.

If I use raspberry pi that can run operating system Linux 
I noticed that the code is programmed for Windows so does the code need to be modified?

**Comment by xiangzhai** [comment]
> I noticed that the code is programmed for Windows so does the code need to be modified?

I already ported to Linux and merged to the upstream:  https://github.com/robopeak/laserkbd

You can try run OpenCV demo on your raspberry pi board plug-in web camera to recognize finger motion.

**Comment by hsayed21** [comment]
Thank you so much @xiangzhai
